version: '3.0'
services:
    jenkins-master:
        image: dirtydriver/jenkinsslave:0.1

        ports:
            - "2222:22"

        volumes:
        - "/opt/jenkins_slave/:/root/workspace"
        - "/var/run/docker.sock:/var/run/docker.sock"
